### ISSUE TITLE
running problems

### ISSUE THREAD

**Issue by hideon27** [Soptq/iccv-3sfc#1]
when i run the code,i got the result below:
 发生异常: RuntimeError
Given groups=1, weight of size [32, 3, 3, 3], expected input[128, 1, 28, 28] to have 3 channels, but got 1 channels instead
  File "C:\Users\...\Desktop\iccv23-3sfc-main\models\ConvNet.py", line 36, in forward
    x = self.gn_relu(conv(x))
  File "C:\Users\...\Desktop\iccv23-3sfc-main\fl_devices.py", line 19, in train_op
    loss = loss_fn(model(x), y)
  File "C:\Users\...\Desktop\iccv23-3sfc-main\fl_devices.py", line 123, in compute_weight_update
    train_stats = train_op(self.model, self.train_loader if not loader else loader, self.optimizer, epochs=epochs, loss_fn=self.loss_fn, device=self.device)
  File "C:\Users\...\Desktop\iccv23-3sfc-main\main.py", line 104, in <module>
    train_stats = client.compute_weight_update(epochs=args.n_client_epoch)
RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[128, 1, 28, 28] to have 3 channels, but got 1 channels instead

so how can i got to solve the problem

**Comment by Soptq** [comment]
Hi @hideon27 , From what you posted, I guess you are using ConvNet on MNIST dataset. ConvNet is designed to process images with 3 channels, like cifar10 or cifar100. MNIST (or FMNIST) has only 1 channel, which causes the error.

**Comment by hideon27** [comment]
OK thanks for the reply，I have successfully run the code, thanks for the patience
